repos:
  - repo: https://github.com/pre-commit/mirrors-black
    rev: v21.12b0
    hooks:
      - id: black
        name: black
        description: "Autoformat Python code using Black"
        language_version: python3.9.5

  - repo: https://github.com/pre-commit/mirrors-flake8
    rev: v4.0.4
    hooks:
      - id: flake8
        name: flake8
        description: "Check Python code for style and linting issues"
        language_version: python3.9.5