from app.api.routers.jobs_router import jobs_router_v1 as jobs_router
from app.api.routers.departments_router import departments_router_v1 as departments_router
from app.api.routers.hired_employees_router import hired_employees_router_v1 as hired_employees_router