# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - dechallenge

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://dechallengecd.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_cc2a1f0285e34bbaa85c6c67bfb6ece4 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_ce0a5eb640d24737b33e8d66eec9f08f }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: dechallengecd.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_cc2a1f0285e34bbaa85c6c67bfb6ece4 }}/de_challenge:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'dechallenge'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_08aa197485d44cac80942ac80267b403 }}
        images: 'dechallengecd.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_cc2a1f0285e34bbaa85c6c67bfb6ece4 }}/de_challenge:${{ github.sha }}'